### ISSUE TITLE
Make default dbpath more sane + clean error that your dbpath is the real problem

### ISSUE THREAD

**Issue by imlucas** [imlucas/mongodb-runner#5]
Even travisci has the `/data` does not exist problem :/  Thinking the default should be the first of the below that is writable:

```javascript
var os = require('os'),
  path = require('path'),
  fs = require('fs-extra'),
  async = require('async');

function dbpath(recipe, fn){
var search = [];
if(os.platform() === 'win32'){
  search.push(path.resolve((process.env.LOCALAPPDATA || process.env.APPDATA), 
    '/mongodb/data/' + recipe.name));
}
else {
   search.push(untildify('~/.mongodb/data/' + recipe.name);
}
search.push(path.resovle(process.cwd(), '/mongodb/data/' + recipe.name));
}
```

```
  0 passing (4m)
  5 failing
  1) runner should start a standalone:
     Error: EACCES, permission denied '/data'
      at Object.fs.mkdirSync (fs.js:647:18)
      at sync (/home/travis/build/imlucas/mongodb-runner/node_modules/mkdirp/index.js:70:13)
      at sync (/home/travis/build/imlucas/mongodb-runner/node_modules/mkdirp/index.js:76:24)
      at Object.sync (/home/travis/build/imlucas/mongodb-runner/node_modules/mkdirp/index.js:76:24)
      at Function.module.exports [as mongod] (/home/travis/build/imlucas/mongodb-runner/lib/bin/mongod.js:161:6)
      at Object.module.exports [as standalone] (/home/travis/build/imlucas/mongodb-runner/recipes/standalone.js:4:14)
      at module.exports (/home/travis/build/imlucas/mongodb-runner/index.js:13:16)
      at Context.<anonymous> (/home/travis/build/imlucas/mongodb-runner/test/index.test.js:6:5)
      at Test.Runnable.run (/home/travis/build/imlucas/mongodb-runner/node_modules/mocha/lib/runnable.js:216:15)
      at Runner.runTest (/home/travis/build/imlucas/mongodb-runner/node_modules/mocha/lib/runner.js:373:10)
      at /home/travis/build/imlucas/mongodb-runner/node_modules/mocha/lib/runner.js:451:12
      at next (/home/travis/build/imlucas/mongodb-runner/node_modules/mocha/lib/runner.js:298:14)
      at /home/travis/build/imlucas/mongodb-runner/node_modules/mocha/lib/runner.js:308:7
      at next (/home/travis/build/imlucas/mongodb-runner/node_modules/mocha/lib/runner.js:246:23)
      at Object._onImmediate (/home/travis/build/imlucas/mongodb-runner/node_modules/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:345:15)
```

cc @TylerBrock

**Comment by imlucas** [comment]
fixed a long time ago
